version: '3'

services:
  scylladb-01:
    image: scylladb/scylla:5.4
    volumes:
      - ./db/scylla1/scylla-data:/var/lib/scylla
      - ./db/scylla1/scylla-commitlog:/var/lib/scylla/commitlog
    networks:
      scylla_net:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD-SHELL", "sh -c $(curl -s -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_service/native_transport')"]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: scylladb-01
    hostname: scylladb-01
    command: "--seeds 172.20.0.2 --cpuset 0 --memory 256M --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-02:
    image: scylladb/scylla:5.4
    volumes:
      - ./db/scylla2/scylla-data:/var/lib/scylla
      - ./db/scylla2/scylla-commitlog:/var/lib/scylla/commitlog
    networks:
      scylla_net:
        ipv4_address: 172.20.0.3
    container_name: scylladb-02
    hostname: scylladb-02
    command: "--seeds 172.20.0.2 --cpuset 1 --memory 256M --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD-SHELL", "sh -c $(curl -s -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_service/native_transport')"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      scylladb-01:
        condition: service_healthy


  # scylladb-03:
  #   image: scylladb/scylla:5.4
  #   networks:
  #     scylla_net:
  #       ipv4_address: 172.20.0.4
  #   container_name: scylladb-03
  #   hostname: scylladb-03
  #   command: "--seeds 172.20.0.2 --cpuset 2 --memory 256M --developer-mode 1 --api-address 127.0.0.1"
  #   cap_add:
  #     - SYS_NICE
  #   healthcheck:
  #     test: ["CMD-SHELL", "sh -c $(curl -s -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_service/native_transport')"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   depends_on:
  #     scylladb-02:
  #       condition: service_healthy

  message-services:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_BACKTRACE=1
    networks:
      scylla_net:
        ipv4_address: 172.20.0.10

networks:
  scylla_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1